const views=[...document.querySelectorAll('.view')];
const links=[...document.querySelectorAll('.sidebar nav a')];
const titles={overview:'Good morning, Soniya 👋',jobs:'Jobs & Placement Drives',applications:'My Applications',assessments:'Assessments',interviews:'Interview Schedule',resume:'Resume Builder',skills:'AI Skill Gap Analyzer',chat:'NexusAI'};
const jobs=[['Microsoft','Software Engineer','Bengaluru','₹18–32 LPA','94%','Python · DSA · SQL'],['Amazon','Data Analyst','Bengaluru','₹12–20 LPA','89%','Python · SQL · Analytics'],['Infosys','Associate Engineer','Mysuru','₹7–10 LPA','86%','Java · SQL · Problem Solving'],['Accenture','AI/ML Analyst','Bengaluru','₹8–14 LPA','91%','Python · ML · SQL'],['Deloitte','Technology Analyst','Hyderabad','₹9–15 LPA','84%','Java · Cloud · SQL'],['IBM','Associate Developer','Pune','₹7–12 LPA','81%','Java · Python · Git']];
function switchView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));links.forEach(a=>a.classList.toggle('active',a.dataset.view===id));document.getElementById('pageTitle').textContent=titles[id]||'';if(id==='jobs')renderJobs(jobs);window.scrollTo({top:0,behavior:'smooth'})}
links.forEach(a=>a.addEventListener('click',()=>switchView(a.dataset.view)));
function renderJobs(list){document.getElementById('jobContainer').innerHTML=list.map((j,i)=>`<article class="job-card"><span class="badge blue">${j[4]} MATCH</span><h3>${j[0]} · ${j[1]}</h3><p>📍 ${j[2]} &nbsp; · &nbsp; 💰 ${j[3]}</p><small>${j[5]}</small><br><br><button class="btn" onclick="applyJob(this)">Apply now</button></article>`).join('')}
function filterJobs(q){const x=q.toLowerCase();renderJobs(jobs.filter(j=>j.join(' ').toLowerCase().includes(x)))}
function applyJob(btn){btn.textContent='Applied ✓';btn.disabled=true;btn.style.background='#12b76a';showToast('Application submitted successfully')}
function startTest(name){showToast(name+' is ready. Timer will start in the full assessment module.')}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function askAI(text){document.getElementById('chatInput').value=text;sendChat(new Event('submit'))}
function sendChat(e){e.preventDefault();const input=document.getElementById('chatInput');const text=input.value.trim();if(!text)return;const box=document.getElementById('messages');box.innerHTML+=`<div class="bubble user">${escapeHtml(text)}</div>`;let answer='Based on your CareerNexus profile, you should focus on your strongest eligible roles and improve the skills highlighted in your AI Skill Gap analysis.';if(/eligible|company/i.test(text))answer='You currently match 12 placement drives. Your strongest matches include Microsoft, Amazon, Accenture and Infosys.';if(/resume/i.test(text))answer='Your current ATS score is 87%. Add measurable project outcomes, relevant keywords and keep your resume to one page.';if(/microsoft/i.test(text))answer='For Microsoft, prioritize DSA, problem solving, OOP, SQL and behavioral preparation. Practice medium-level coding problems and explain your approach clearly.';setTimeout(()=>{box.innerHTML+=`<div class="bubble ai">${answer}</div>`;box.scrollTop=box.scrollHeight},350);input.value=''}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
renderJobs(jobs);
