const CN_KEY='careernexus_shared_v1';
const CN_DEFAULT={applications:[{id:'APP-1001',student:'R Soniya',studentId:'1VT23AI001',company:'Microsoft',job:'Software Engineer',status:'Interview',applied:'2026-09-29'},{id:'APP-1002',student:'Aarav Kumar',studentId:'1VT23CS014',company:'Amazon',job:'Data Analyst',status:'Shortlisted',applied:'2026-09-27'},{id:'APP-1003',student:'Rahul M',studentId:'1VT23IS022',company:'Infosys',job:'Associate Engineer',status:'Under Review',applied:'2026-09-25'}],assessments:[{id:'ASM-1',student:'R Soniya',company:'Amazon',title:'Amazon Technical Assessment',status:'Assigned',score:null}],interviews:[{id:'INT-1',student:'R Soniya',company:'Microsoft',job:'Software Engineer',round:'Technical Round 2',date:'2026-10-11',time:'14:30',mode:'Virtual',status:'Scheduled'}],notifications:[{id:'N-1',student:'R Soniya',text:'Microsoft technical interview scheduled for Oct 11.',read:false},{id:'N-2',student:'R Soniya',text:'Amazon Technical Assessment is available.',read:false}]};
function cnLoad(){try{return JSON.parse(localStorage.getItem(CN_KEY))||JSON.parse(JSON.stringify(CN_DEFAULT))}catch(e){return JSON.parse(JSON.stringify(CN_DEFAULT))}}
function cnSave(data){localStorage.setItem(CN_KEY,JSON.stringify(data));window.dispatchEvent(new Event('careernexus-sync'))}
function cnApply(o){o=o||{};o.student=o.student||'R Soniya';o.studentId=o.studentId||'1VT23AI001';const d=cnLoad();if(d.applications.some(a=>a.studentId===o.studentId&&a.company===o.company&&a.job===o.job))return false;d.applications.push({id:'APP-'+Date.now(),student:o.student,studentId:o.studentId,company:o.company,job:o.job,status:'Applied',applied:new Date().toISOString().slice(0,10)});d.notifications.unshift({id:'N-'+Date.now(),student:o.student,text:'Application submitted for '+o.job+' at '+o.company+'.',read:false});cnSave(d);return true}
function cnUpdateApplication(id,status){const d=cnLoad(),a=d.applications.find(x=>x.id===id);if(!a)return;a.status=status;d.notifications.unshift({id:'N-'+Date.now(),student:a.student,text:'Your '+a.job+' application at '+a.company+' is now '+status+'.',read:false});cnSave(d)}
function cnAssignAssessment(o){const d=cnLoad();d.assessments.push({id:'ASM-'+Date.now(),student:o.student,company:o.company,title:o.title,status:'Assigned',score:null});d.notifications.unshift({id:'N-'+Date.now(),student:o.student,text:'New assessment assigned by '+o.company+': '+o.title+'.',read:false});cnSave(d)}
function cnScheduleInterview(o){const d=cnLoad();d.interviews.push({id:'INT-'+Date.now(),student:o.student,company:o.company,job:o.job,round:o.round,date:o.date,time:o.time,mode:o.mode||'Virtual',status:'Scheduled'});d.notifications.unshift({id:'N-'+Date.now(),student:o.student,text:'Interview scheduled: '+o.company+' '+o.round+' on '+o.date+' at '+o.time+'.',read:false});cnSave(d)}
function cnNotifications(student){return cnLoad().notifications.filter(n=>n.student===(student||'R Soniya'))}
